forum/models/message.py
from . import models
from ..db import db
from datetime import datetime
import pytz


# Return all the connections of user
def get_connections(user):
    connection_as_sender = models.Connection.query.filter_by(sender=user, status=0).with_entities(
        models.Connection.receiver.label('username'), models.Connection.last_contact_datetime)

    connection_as_receiver = models.Connection.query.filter_by(receiver=user, status=0).with_entities(
        models.Connection.sender.label('username'), models.Connection.last_contact_datetime)

    return connection_as_sender.union(connection_as_receiver).order_by(
        models.Connection.last_contact_datetime.desc()).with_entities(db.column('username')).all()


# Return all the message history between user1 and user2
def get_message_history(user1, user2):
    return models.Message.query.filter_by(sender=user1, receiver=user2).union(
        models.Message.query.filter_by(sender=user2, receiver=user1)).order_by(
        models.Message.sent_datetime).all()


# Insert into database of the sent message
# Also update the last_contact_datetime of the connection between sender and receiver
def send_message(sender, receiver, content):
    tz = pytz.timezone('US/Central')
    cur_time = datetime.now(tz=tz)
    new_message = models.Message(sender, receiver, content, cur_time)

    db.session.add(new_message)
    db.session.commit()

    models.Connection.query.filter_by(sender=sender, receiver=receiver).update(
        {'last_contact_datetime': cur_time})
    models.Connection.query.filter_by(receiver=sender, sender=receiver).update(
        {'last_contact_datetime': cur_time})
    db.session.commit()

    return new_message


# Delete all private message
# For testing
def delete_all_pm():
    models.Message.query.delete()
    db.session.commit()


# Search user by username
def search_user(keyword):
    return models.User.query.filter_by(username=keyword).all()


# Insert into database the connection request from sender to receiver
def send_connection_request(sender, receiver):
    tz = pytz.timezone('US/Central')
    cur_time = datetime.now(tz=tz)
    connection_request = models.Connection(sender, receiver, 1, cur_time)

    db.session.add(connection_request)
    db.session.commit()

    return connection_request


# Update the connection request to connection between sender and receiver
def add_connection(sender, receiver):
    tz = pytz.timezone('US/Central')
    cur_time = datetime.now(tz=tz)
    models.Connection.query.filter_by(sender=sender, receiver=receiver).update(
        {'last_contact_datetime': cur_time, 'status': 0}
    )
    db.session.commit()


# Delete the connection request from sender to receiver
def delete_connection_request(sender, receiver):
    models.Connection.query.filter_by(
        sender=sender, receiver=receiver, status=1).delete()
    db.session.commit()


# Delete the connection between sender and receiver
def delete_connection(sender, receiver):
    models.Connection.query.filter_by(
        sender=sender, receiver=receiver, status=0).delete()
    models.Connection.query.filter_by(
        sender=receiver, receiver=sender, status=0).delete()
    db.session.commit()


# Return true if there is already a connection request from sender to receiver
def check_request_exist(sender, receiver):
    check = models.Connection.query.filter_by(sender=sender, receiver=receiver, status=1).union(
        models.Connection.query.filter_by(sender=receiver, receiver=sender, status=1)).all()
    return len(check) != 0


# Return all pending connection requests sent by the current user
def get_pending_sent_request(user):
    return models.Connection.query.filter_by(sender=user, status=1).order_by(
        models.Connection.last_contact_datetime.desc()).all()


# Return all the pending connections waiting for current user's approval
def get_pending_received_request(user):
    return models.Connection.query.filter_by(receiver=user, status=1).order_by(
        models.Connection.last_contact_datetime.desc()).all()

forum/views/index.py
from flask import render_template, request, Blueprint
from ..models import post


# Register blueprint
blueprint = Blueprint('index', __name__)


# Route for the index page
@blueprint.route('/')
def index():
    posts = post.list_all_posts()
    return render_template('index.html', posts=posts)


@blueprint.route('/hello')
def hello():
    return 'Hello, World!'


@blueprint.route('/profile.html')
def profile():
    return render_template('profile.html')


# Search post using keywords
@blueprint.route('/search', methods=('GET', 'POST'))
def search():
    posts = post.list_all_posts()
    if request.method == 'POST':
        keyword = request.form['keyword']

        if not keyword:
            return render_template("index.html", posts=posts)
        else:
            posts = post.search_post_by_keyword(keyword)
            return render_template("index.html", posts=posts)

    return render_template("index.html", posts=posts)

forum/views/message.py
from flask import flash, redirect, render_template, request, Blueprint, url_for, session
from ..models import message


# Register blueprint
blueprint = Blueprint('message', __name__, url_prefix='/pm/')


# Return page for messaging
# cur_conversation: user to send message to
# Login required, or will redirect to login page
@blueprint.route('/message', methods=('GET', 'POST'))
def message_index():
    if not session.get('user_id'):
        flash('Login required.')
        return redirect(url_for('user.login'))

    args = request.args.to_dict()
    cur_user = session.get('user_id')

    if args:
        cur_conversation = args['conversation']
    else:
        cur_conversation = ''

    if request.method == 'POST':
        message.send_message(cur_user, cur_conversation,
                             request.form['content'])

    connections = message.get_connections(cur_user)
    message_history = message.get_message_history(
        cur_user, cur_conversation)

    return render_template('message.html', connections=connections,
                           cur_conversation=cur_conversation, message_history=message_history)


# Return page for connection management
@blueprint.route('/connection_management', methods=('GET', 'POST'))
def connection_management():
    cur_user = session.get('user_id')
    search_result = ""

    if request.method == 'POST':
        dict = request.form.to_dict()

        # For searching user
        if "username" in dict.keys():
            username = dict['username']
            find = message.search_user(username)
            connections = message.get_connections(cur_user)
            connection_exist = False
            for connection in connections:
                if connection.username == username:
                    connection_exist = True

            if len(find) != 1 or find[0].username == cur_user:
                flash('No matching result')
            elif connection_exist:
                flash('User already connected')
            else:
                search_result = find[0]

        # For sending connection request to the searched user
        elif "send_connection" in dict.keys():
            username = dict['send_connection']
            if message.check_request_exist(cur_user, username):
                flash('Connection request already exist')
            else:
                message.send_connection_request(cur_user, username)
                flash('Connection request sent')

        # For accepting a received pending connection request
        elif "accept_connection" in dict.keys():
            print('accc')
            username = dict['accept_connection']
            message.add_connection(username, cur_user)
            message.delete_connection_request(username, cur_user)

        # For declining a received pending connection request
        elif "decline_connection" in dict.keys():
            username = dict['decline_connection']
            message.delete_connection_request(username, cur_user)

        # For deleting a current existing connection
        elif "delete_connection" in dict.keys():
            username = dict['delete_connection']
            message.delete_connection(username, cur_user)

    connections = message.get_connections(cur_user)
    pending_sent_request = message.get_pending_sent_request(cur_user)
    pending_received_request = message.get_pending_received_request(cur_user)

    return render_template('connection.html', connections=connections, pending_sent_request=pending_sent_request,
                           search_result=search_result, pending_received_request=pending_received_request)

forum/views/user.py
from flask import flash, redirect, render_template, request, Blueprint, url_for, session
from ..models import authentication
from ..models.post import get_all_favoutites, get_user_upvote_num


# Register blueprint for user operations
blueprint = Blueprint('user', __name__, url_prefix='/user/')


# Register page:
# Flash warning messages when username or password is not given or when username already exists
# Redirect to login page if registered successfully
@blueprint.route('/register', methods=('GET', 'POST'))
def register():
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']
        message = None

        if not username:
            message = 'Username is required.'
        elif not password:
            message = 'Password is required.'
        else:
            all_users = authentication.list_all_user()
            username_exist = False
            for user in all_users:
                if username == user.username:
                    username_exist = True
            if username_exist:
                message = 'Username exists.'
            else:
                authentication.create_user(username, password)
                return redirect(url_for('user.login'))

        flash(message)

    return render_template('auth/register.html')


# Login page:
# Flash warning messages when username or password is not given
#                       or when username and password doesn't match
# Redirect to index page and register user in session if logged in successfully
@blueprint.route('/login', methods=('GET', 'POST'))
def login():

    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']
        message = None

        if not username:
            message = 'Username is required.'
        elif not password:
            message = 'Password is required.'
        else:
            message = authentication.check_password(username, password)

            if message != "Username doesn't exist." and message != "Password incorrect.":
                session.clear()
                session['user_id'] = message.username
                return redirect(url_for('index.index'))

        flash(message)

    return render_template('auth/login.html')


# Logout page
# Clear session
@blueprint.route('/logout')
def logout():
    session.clear()
    return redirect(url_for('index.index'))


# Delete all users
@blueprint.route('/clean')
def clean():
    return authentication.delete_all_user()


# List all users
@blueprint.route('/list')
def list():
    users = authentication.list_all_user()
    user_list = []
    for user in users:
        user_list.append(user.username)
    return user_list


# Profile page
@blueprint.route('/profile')
def profile():
    posts = get_all_favoutites(session.get('user_id'))
    num_upvote = get_user_upvote_num(session.get('user_id'))
    return render_template('profile.html', posts=posts, num_upvote=num_upvote)

forum/templates/connection.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <a class="action" href="{{ url_for('message.message_index') }}">Back</a>

    <form method="post">
        <label for="Add connection">Search for user to connect with:</label>
        <input name="username" id="username">
        <input type="submit" value="Search">
    </form>
    {% if search_result %}
    <p>{{search_result.username}}</p>
    <form method="post">
        <input type="hidden" id="send_connection" name="send_connection" value={{search_result.username}}>
        <input type="submit" value="Connect">
    </form>
    {% endif %}
    {% for message in get_flashed_messages() %}
    <p>{{ message }}</p>
    {% endfor %}

    <br><br><br>

    {% if pending_sent_request or pending_received_request %}
    <p>Pending:</p>
    <hr>

    {% for pending_connection in pending_sent_request %}
    <p>{{pending_connection.receiver}}</p>
    <p>Request sent</p>
    <hr>
    {% endfor %}

    {% for pending_connection in pending_received_request %}
    <p>{{pending_connection.sender}}</p>
    <form method="post">
        <input type="hidden" id="accept_connection" name="accept_connection" value={{pending_connection.sender}}>
        <input type="submit" value="Accept">
    </form>
    <form method="post">
        <input type="hidden" id="decline_connection" name="decline_connection" value={{pending_connection.sender}}>
        <input type="submit" value="Decline">
    </form>
    <hr>
    {% endfor %}
    <br><br><br>
    {% endif %}



    <p>Connections:</p>
    <hr>
    {% if connections == [] %}
    <p>No connections</p>
    {% endif %}

    {% for connection in connections %}
    <p>{{connection.username}}</p>
    <form method="post">
        <input type="hidden" id="delete_connection" name="delete_connection" value={{connection.username}}>
        <input type="submit" value="Delete">
    </form>
    <hr>
    {% endfor %}
</body>

</html>

forum/templates/index.html
<!DOCTYPE html>
<html lang="en">

<head>


  <style type="text/css">
    body {
      margin: 0px;
    }

    div#top {
      width: 100%;
      height: 100px;
      background-color: aliceblue;
    }

    div#topleft {
      float: left;
      margin-left: 10px;
      width: 200px;
      height: 100px;
    }

    div#topmiddle {
      float: left;
      margin-left: 36.3%;
      height: 100px;
      font-size: xx-large;
      font-weight: bolder;
      line-height: 100px;

    }

    div#topright {
      margin-left: 85%;
      height: 100px;
      line-height: 100px;
    }

    div#post_region {
      margin-top: 50px;
      padding-left: 20%;
      padding-right: 20%;
      width: 100%;
      height: 100%;
      word-wrap: break-word;
      width:60%;
    }

    div#offset {
      height: 10px;
    }
  </style>

  <title>Chat Forum</title>
  <link rel="icon" type="image/x-icon" href="favicon.ico">
  <link rel="stylesheet" href="{{url_for('static',filename='style.css')}}" />

</head>

<body>
  <div id="top">

    <div id="topleft">
      <nav>
        <ul>
          {% if session.get('user_id') %}
          <li><span>{{ 'Welcome, '+session.get('user_id') }}</span>
          <li><a href="{{ url_for('post.create_post') }}">New post</a>
          <li><a href="{{ url_for('user.logout') }}">Log Out</a>
            {% else %}
          <li><a href="{{ url_for('user.register') }}">Register</a>
          <li><a href="{{ url_for('user.login') }}">Log In</a>
            {% endif %}
        </ul>
      </nav>
    </div>

    <div id="topmiddle">

      Chat Forum

    </div>

    <div id="topright">
      <link href="{{url_for('static',filename='home.css')}}" rel="stylesheet" />

      <form action="{{url_for('index.search')}}" method="post">
        <input name="keyword" id="keyword" placeholder="Enter keyword">
        <input type="submit" value="Search">
      </form>
    </div>



  </div>

  <div>
    <div id="offset">


    </div>

    <div class="home-container">

      <nav class="homehead-nav homehead-root-class-name18">
        <a href="{{url_for('index.index')}}" class="homehead-text"><span>Home</span></a>

        <a href="{{url_for('message.message_index')}}" class="homehead-navlink1">
          <span>Message</span>
        </a>
        <a href="{{url_for('user.profile')}}" class="homehead-navlink2">
          <span>Profile</span>
        </a>
      </nav>
      <div data-type="AccordionHeader" class="home-accordion-header">
        <svg viewBox="0 0 1024 1024" class="home-icon">
          <path
            d="M128 554.667h768c23.552 0 42.667-19.115 42.667-42.667s-19.115-42.667-42.667-42.667h-768c-23.552 0-42.667 19.115-42.667 42.667s19.115 42.667 42.667 42.667zM128 298.667h768c23.552 0 42.667-19.115 42.667-42.667s-19.115-42.667-42.667-42.667h-768c-23.552 0-42.667 19.115-42.667 42.667s19.115 42.667 42.667 42.667zM128 810.667h768c23.552 0 42.667-19.115 42.667-42.667s-19.115-42.667-42.667-42.667h-768c-23.552 0-42.667 19.115-42.667 42.667s19.115 42.667 42.667 42.667z">
          </path>
        </svg>
      </div>


      <!-- post region -->

      <div id="post_region">

        </header>
        {% for post in posts %}
        <article class="post">
          <header>
            <div>
              <a class="action" href="{{ url_for('post.view_post', id=post.id) }}">{{post.title}}</a>
              <div class="about">by {{ post['author'] }} on {{ post['create_datetime'].strftime('%Y-%m-%d %H:%M:%S') }}
              </div>
            </div>
          </header>
          <p class="body">{{ post['content'] }}</p>
        </article>



        {% if not loop.last %}
        <hr>
        {% endif %}
        {% endfor %}
      </div>

    </div>


  </div>

</body>

</html>

forum/templates/message.html
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Message - Chat Forum</title>

    <link rel="stylesheet" href="{{url_for('static',filename='style.css')}}" />


    <style type="text/css">
        body {
            margin: 0px;
            height: 100%;
            width: 100%;
        }

        div#container {
            width: 100%;
            height: 100%;
        }

        div#userlist {
            width: 25%;
            height: 825px;
            background-color: ghostwhite;
            float: left;
        }

        div#message {
            width: 75%;
            height: 825px;
            float: left;
        }

        div#message_display {
            width: 100%;
            height: 495px;
        }

        div#message_send {
            width: 100%;
            height: 330px;
        }

        div#message_send_content {
            width: 90%;
            height: 330px;
            ;
            float: left;
        }

        div#message_send_send {
            width: 10%;
            height: 330px;
            ;
            float: left;
        }


        div#headline {
            width: 100%;
            height: 150px;
            background-color: aliceblue;
            font-size: 20px;
        }

        div#mainbody {
            width: 100%;
            height: 825px;
        }

        #content {
            width: 100%;
            height: 309px;
        }

        #send {
            width: 100%;
            height: 315px;
        }

        div#friendname {
            width: 100%;
            height: 40px;
            text-align: center;
            font-size: 30px;
            padding-top: 10px;
        }

        div#back {
            float: left;
            width: 5%;
            line-height: 50px;
            text-align: center;
        }

        div#co_manage {
            margin-left: 85%;
            line-height: 50px;
        }
    </style>
</head>



<body>
    <div id="container">
        <!-- headline -->
        <div id="headline">
            <div id="back">
                <a class="action" href="{{ url_for('index.index') }}">Back</a>
            </div>

            <div id="co_manage">
                <a class="action" href="{{ url_for('message.connection_management') }}">Connection management</a>
            </div>
        </div>

        <!-- mainbody -->
        <div id="mainbody">

            <!-- left->userlist -->
            <div id="userlist">
                {% for connection in connections %}
                <article class="message">
                    <header>
                        <div id=friendname>
                            <a class="action"
                                href="{{ url_for('message.message_index', conversation=connection.username) }}">{{connection.username}}</a>
                        </div>

                    </header>

                </article>
                <hr>
                {% endfor %}

            </div>

            <!-- right->message -->
            <div id="message">
                {% if not cur_conversation%}

                {% else %}

                <div id="message_display">
                    <p>Messages with {{cur_conversation}}:</p>
                    {% if not message_history%}
                    <!-- <p>Also blank here</p> -->
                    {% else %}
                    {% for message in message_history %}
                    {{message.sender}} says: {{message.content}} at {{message.sent_datetime}} <br>
                    {% if not loop.last %}
                    <!-- <hr> -->
                    {% endif %}
                    {% endfor %}

                    {% endif %}
                </div>

                <div id="message_send">

                    <form method="post">
                        <div id="message_send_content">
                            <input type="text" name="content" id="content">
                        </div>

                        <div id="message_send_send">
                            <input type="submit" value="Send" id="send">
                        </div>
                    </form>
                </div>
                {% endif %}



            </div>
        </div>
    </div>

    <div>



    </div>

</body>

</html>

forum/templates/profile.html
<!DOCTYPE html>
<html lang="en">

<head>
  <style type="text/css">
    body {
      margin: 0px;
    }

    div#top {
      width: 100%;
      height: 100px;
      background-color: aliceblue;
    }

    div#topleft {
      float: left;
      margin-left: 10px;
      width: 200px;
      height: 100px;
    }

    div#topmiddle {
      float: left;
      margin-left: 36.3%;
      height: 100px;
      font-size: xx-large;
      font-weight: bolder;
      line-height: 100px;

    }

    div#topright {
      margin-left: 85%;
      height: 100px;
      line-height: 100px;
    }

    div#post_region {
      margin-top: 50px;
    }

    div#offset {
      height: 10px;

    }


    div#information {

      font-size:large;
    }


    div#favorite {
      margin-top: 100px;
      font-size:large;
      font-weight: bolder;
      height:50px;
    }

    div#favorite_post {
      font-family:'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif;
      font-style: italic;
    }

  </style>


  <title>Profile - Chat Forum</title>
  <meta property="og:title" content="Profile - Chat Forum" />

  <link rel="stylesheet" href="{{url_for('static',filename='style.css')}}" />

</head>

<body>
  <div id="top">

    <div id="topleft">
      <nav>
        <ul>
          {% if session.get('user_id') %}
          <li><span>{{ 'Welcome, '+session.get('user_id') }}</span>
          <li><a href="{{ url_for('post.create_post') }}">New post</a>
          <li><a href="{{ url_for('user.logout') }}">Log Out</a>
            {% else %}
          <li><a href="{{ url_for('user.register') }}">Register</a>
          <li><a href="{{ url_for('user.login') }}">Log In</a>
            {% endif %}
        </ul>
      </nav>
    </div>

    <div id="topmiddle">

      Chat Forum

    </div>

    <div id="topright">
      <link href="{{url_for('static',filename='home.css')}}" rel="stylesheet" />

      <form action="{{url_for('index.search')}}" method="post">
        <input name="keyword" id="keyword" placeholder="Enter keyword">
        <input type="submit" value="Search">
      </form>
    </div>



  </div>

  <div>
    <div id="offset">


    </div>

    <div class="home-container">

      <nav class="homehead-nav homehead-root-class-name18">
        <a href="{{url_for('index.index')}}" class="homehead-text"><span>Home</span></a>

        <a href="{{url_for('message.message_index')}}" class="homehead-navlink1">
          <span>Message</span>
        </a>

        <a href="{{url_for('user.profile')}}" class="homehead-navlink2">
          <span>Profile</span>
        </a>
      </nav>
      <div data-type="AccordionHeader" class="home-accordion-header">
        <svg viewBox="0 0 1024 1024" class="home-icon">
          <path
            d="M128 554.667h768c23.552 0 42.667-19.115 42.667-42.667s-19.115-42.667-42.667-42.667h-768c-23.552 0-42.667 19.115-42.667 42.667s19.115 42.667 42.667 42.667zM128 298.667h768c23.552 0 42.667-19.115 42.667-42.667s-19.115-42.667-42.667-42.667h-768c-23.552 0-42.667 19.115-42.667 42.667s19.115 42.667 42.667 42.667zM128 810.667h768c23.552 0 42.667-19.115 42.667-42.667s-19.115-42.667-42.667-42.667h-768c-23.552 0-42.667 19.115-42.667 42.667s19.115 42.667 42.667 42.667z">
          </path>
        </svg>
      </div>

      <!-- post region -->
      

      <div id="post_region">

        <div id="information">
          <p>Username: {{session.get('user_id')}}</p>
          <p>Total upvotes got: {{num_upvote}}</p>

        </div>

        <div id="favorite">
          <p>Favourites:</p><br>
        </div>


        <div>
          {% for post in posts %}
          <article class="post">
            <div>
                <a class="action" href="{{ url_for('post.view_post', id=post[1].id) }}">{{post[1].title}}</a>
                <div id="favorite_post">
                  <div class="about">by {{ post[1]['author'] }} on {{ post[1]['create_datetime'].strftime('%Y-%m-%d
                    %H:%M:%S') }}
                  </div>
                </div>
              </div>
              <p class="body">{{ post[1]['content'] }}</p>
          </article>

          {% if not loop.last %}
          <hr>
          {% endif %}
          {% endfor %}
      </div>

    </div>


  </div>

</body>

</html>

forum/templates/sign-up.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>sign-up - Chat Forum</title>
    <meta property="og:title" content="sign-up - Chat Forum" />

    <style data-tag="reset-style-sheet">
      html {  line-height: 1.15;}body {  margin: 0;}* {  box-sizing: border-box;  border-width: 0;  border-style: solid;}p,li,ul,pre,div,h1,h2,h3,h4,h5,h6 {  margin: 0;  padding: 0;}button {  background-color: transparent;}button,input,optgroup,select,textarea {  font-family: inherit;  font-size: 100%;  line-height: 1.15;  margin: 0;}button,select {  text-transform: none;}button,[type="button"],[type="reset"],[type="submit"] {  -webkit-appearance: button;}button::-moz-focus-inner,[type="button"]::-moz-focus-inner,[type="reset"]::-moz-focus-inner,[type="submit"]::-moz-focus-inner {  border-style: none;  padding: 0;}button:-moz-focus,[type="button"]:-moz-focus,[type="reset"]:-moz-focus,[type="submit"]:-moz-focus {  outline: 1px dotted ButtonText;}a {  color: inherit;  text-decoration: inherit;}input {  padding: 2px 4px;}img {  display: block;}html { scroll-behavior: smooth  }
    </style>
    <style data-tag="default-style-sheet">
      html {
        font-family: Inter;
        font-size: 16px;
      }

      body {
        font-weight: 400;
        font-style:normal;
        text-decoration: none;
        text-transform: none;
        letter-spacing: normal;
        line-height: 1.15;
        color: var(--dl-color-gray-black);
        background-color: var(--dl-color-gray-white);

      }
    </style>
    <link
      rel="stylesheet"
      href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800;900&amp;display=swap"
      data-tag="font"
    />
    <!--This is the head section-->
    <!-- <style> ... </style> -->
    <link rel="stylesheet" href="./style.css" />
  </head>
  <body>
    <div>
      <link href="./sign-up.css" rel="stylesheet" />

      <div class="sign-up-container">
        <div class="signuptypebox-container signuptypebox-root-class-name">
          <div class="signuptypebox-container1">
            <span class="signuptypebox-text"><span>Username</span></span>
            <input type="text" placeholder="placeholder" class="input" />
          </div>
          <div class="signuptypebox-container2">
            <div class="signuptypebox-container3">
              <span class="signuptypebox-text1"><span>Password</span></span>
            </div>
            <input
              type="text"
              placeholder="placeholder"
              class="signuptypebox-textinput1 input"
            />
          </div>
        </div>
        <a href="login.html" class="sign-up-navlink button">
          <span>Sign Up</span>
        </a>
        <a href="login.html" class="sign-up-navlink1">Login</a>
      </div>
    </div>
    <script
      data-section-id="header"
      src="https://unpkg.com/@teleporthq/teleport-custom-scripts"
    ></script>
  </body>
</html>