forum/models/post.py
from datetime import datetime
from . import models
from ..db import db
import pytz


# Return all posts in the database
def list_all_posts():
    return models.Post.query.order_by(models.Post.create_datetime.desc())


# Get post by id
def get_post(id):
    return models.Post.query.filter_by(id=id).one()


# Create a new post using the title, content, and author_id parameters
def create_post(title, content, user_id):
    tz = pytz.timezone('US/Central')
    cur_time = datetime.now(tz=tz)
    new_post = models.Post(title, user_id, cur_time, content)

    db.session.add(new_post)
    db.session.commit()

    return new_post


# Update the post with id as post_id using new title and content
def update_post(title, content, id):
    models.Post.query.filter_by(id=id).update(
        {'title': title, 'content': content})
    db.session.commit()


# Delete the post with id as post_id
def delete_post(id):
    models.Post.query.filter_by(id=id).delete()
    db.session.commit()


# Delete all post
def delete_all_post():
    models.Post.query.delete()
    db.session.commit()


# Search post by keyword,
# keyword could be part of the post's title, content, or author
def search_post_by_keyword(keyword):
    search = "%{}%".format(keyword)
    posts = models.Post.query.filter(models.Post.title.like(search)).union(
        models.Post.query.filter(models.Post.content.like(search))).union(
            models.Post.query.filter(models.Post.author.like(search))).order_by(
                models.Post.create_datetime.desc()).all()
    return posts


# Upvote post
def upvote_post(user_id, post_id):
    tz = pytz.timezone('US/Central')
    cur_time = datetime.now(tz=tz)
    upvote = models.Upvote(user_id, post_id, cur_time)
    db.session.add(upvote)
    db.session.commit()


# Unupvote post
def unupvote_post(user_id, post_id):
    models.Upvote.query.filter_by(user_id=user_id, post_id=post_id).delete()
    db.session.commit()


# Check if user has upvoted the post
def check_upvoted(user_id, post_id):
    upvoted = models.Upvote.query.filter_by(
        user_id=user_id, post_id=post_id).all()
    return len(upvoted) == 1


# Get the number of upvotes of the post
def get_upvote_num(post_id):
    return len(models.Upvote.query.filter_by(post_id=post_id).all())


# Favourite post
def favourite_post(user_id, post_id):
    tz = pytz.timezone('US/Central')
    cur_time = datetime.now(tz=tz)
    favourite = models.Favourite(user_id, post_id, cur_time)
    db.session.add(favourite)
    db.session.commit()


# Unfavourite post
def unfavourite_post(user_id, post_id):
    models.Favourite.query.filter_by(user_id=user_id, post_id=post_id).delete()
    db.session.commit()


# Check if user has favourited the post
def check_favourited(user_id, post_id):
    favourited = models.Favourite.query.filter_by(
        user_id=user_id, post_id=post_id).all()
    return len(favourited) == 1


# Get all favourites of the user
def get_all_favoutites(user_id):
    return db.session.query(models.Favourite, models.Post).filter_by(user_id=user_id).join(models.Post).order_by(models.Favourite.time.desc()).all()


# Get the total number of upvotes a user get
def get_user_upvote_num(user_id):
    upvotes = db.session.query(models.Upvote, models.Post).join(
        models.Post).filter_by(author=user_id).all()
    return len(upvotes)


# Create new reply for the given post
def create_reply(post_id, reply_id, author, content):
    tz = pytz.timezone('US/Central')
    cur_time = datetime.now(tz=tz)
    reply = models.Reply(post_id, reply_id, author, content, cur_time)
    db.session.add(reply)
    db.session.commit()


# Get all reply for the given post_id
def get_reply(post_id):
    return models.Reply.query.filter_by(post_id=post_id).order_by(models.Reply.time).all()

forum/views/post.py
from flask import flash, redirect, render_template, request, Blueprint, url_for, session
from ..models import post


# Register blueprint
blueprint = Blueprint('post', __name__, url_prefix='/post/')


# Edit post page for given post_id
@blueprint.route('/edit', methods=('GET', 'POST'))
def edit_post():
    id = request.args.to_dict()['id']
    if request.method == 'POST':
        title = request.form['title']
        content = request.form['content']
        message = None

        if not title:
            message = 'Title is required.'
        else:
            # try:
            post.update_post(title, content, id)
            return redirect(url_for('index.index'))
            # except:

        flash(message)
    return render_template("post/edit_post.html", post=post.get_post(id))


# View post page
# If session user equals to author, button for delete and edit will be shown
@blueprint.route('/view')
def view_post():
    id = request.args.to_dict()['id']
    return render_template("post/post.html", post=post.get_post(id),
                           upvote_num=post.get_upvote_num(id),
                           upvoted=post.check_upvoted(
                               session.get('user_id'), id),
                           favourited=post.check_favourited(
                               session.get('user_id'), id),
                           replies=post.get_reply(id))


# Delete post page, redirects to index page
@blueprint.route('/delete')
def delete_post():
    id = request.args.to_dict()['id']
    post.delete_post(id)
    return redirect(url_for('index.index'))


# Create post page
@blueprint.route('/create', methods=('GET', 'POST'))
def create_post():
    if request.method == 'POST':
        title = request.form['title']
        content = request.form['content']
        message = None

        if not title:
            message = 'Title is required.'
        else:
            post.create_post(title, content, session.get('user_id'))
            return redirect(url_for('index.index'))

        flash(message)

    return render_template("post/create_post.html")


# Upvote post
@blueprint.route('/upvote', methods=('GET', 'POST'))
def upvote():
    id = request.args.to_dict()['id']
    post.upvote_post(session.get('user_id'), id)
    return redirect(url_for('post.view_post', id=id))


# Unupvote post
@blueprint.route('/unupvote', methods=('GET', 'POST'))
def unupvote():
    id = request.args.to_dict()['id']
    post.unupvote_post(session.get('user_id'), id)
    return redirect(url_for('post.view_post', id=id))


# Favourite post
@blueprint.route('/favourite', methods=('GET', 'POST'))
def favourite():
    id = request.args.to_dict()['id']
    post.favourite_post(session.get('user_id'), id)
    return redirect(url_for('post.view_post', id=id))


# Unfavourite post
@blueprint.route('/unfavourite', methods=('GET', 'POST'))
def unfavourite():
    id = request.args.to_dict()['id']
    post.unfavourite_post(session.get('user_id'), id)
    return redirect(url_for('post.view_post', id=id))


# Reply to a post
@blueprint.route('/reply', methods=('GET', 'POST'))
def reply():
    post_id = request.args.to_dict()['id']
    replies = post.get_reply(post_id)
    if request.method == 'POST':
        content = request.form['content']
        message = None

        if not content:
            message = 'Reply is blank.'
        else:
            post.create_reply(post_id, len(replies)+1,
                              session.get('user_id'), content)
            return redirect(url_for('post.view_post', id=post_id))

        flash(message)

    return "Reply page (Access from view post)"

forum/templates/post/create_post.html
<!DOCTYPE html>
<html lang="en">

<head>
  <title>Create post - Chat Forum</title>

  <link rel="stylesheet" href="{{url_for('static',filename='style.css')}}" />
  <style type="text/css">
    body {
      margin:0px;
    }
    div#back{
      margin-left: 10px;
      width: 100%;
      height: 30px;
    }

    div#container {
      text-align:center;
    }

    div#title {
      text-align:center;
      width: 100%;
      height: 50px;
      font-size:x-large;
      font-weight: bold;
    }

    #title_box {  
      width:1000px;
      height: 60px;
      padding: 10px;
      font-size: large;
    }

    #reply_box {  
      width:1000px;
      height: 250px;
      padding: 10px;
      font-size: large;
    }

  
  </style>
</head>

<body>

    <div id = back>
      <a class="action" href="{{ url_for('index.index') }}">Back</a>
    </div>

    <div id = container>

      <br><br><br><br> 

      <form method="post">
        <div id = title>
          <label for="title">Title</label>
        </div>

        <input name="title" id="title_box">
        <br><br><br>

        <!-- <input name="content" id="content"> -->

        <div id = title>
          <label for="content">Content</label>
        </div>

        <textarea  name="content" id="reply_box"></textarea> 
        <br><br><br>

        <input type="submit" value="Post">

      </form>
      {% for message in get_flashed_messages() %}
      <div class="flash">{{ message }}</div>
      {% endfor %}


    </div>

</body>

</html>

forum/templates/post/edit_post.html
<!DOCTYPE html>
<html lang="en">

<head>
  <title>Edit post - Chat Forum</title>

  <link rel="stylesheet" href="{{url_for('static',filename='style.css')}}" />

  <style type="text/css">
    body {
      margin:0px;
    }
    div#back{
      margin-left: 10px;
      width: 100%;
      height: 30px;
    }

    div#container {
      text-align:center;
    }

    div#title {
      text-align:center;
      width: 100%;
      height: 50px;
      font-size:x-large;
      font-weight: bold;
    }

    #title_box {  
      width:1000px;
      height: 60px;
      padding: 10px;
      font-size: large;
    }

    #reply_box {  
      width:1000px;
      height: 250px;
      padding: 10px;
      font-size: large;
    }

  
  </style>
</head>

<body>
  <div id = back>
    <a class="action" href="{{ url_for('index.index') }}">Back</a>
  </div>

  <div id = container>

    <br><br><br><br> 

    <form method="post">
      <div id = title>
        <label for="title">Title</label>
      </div>
      <input name="title" id="title_box" value="{{post.title}}">
      <br><br><br>

      <!-- <input name="content" id="content" value="{{post.content}}"> -->

      <div id = title>
        <label for="content">Content</label>
      </div>
      <textarea  name="content" id="reply_box" >{{post.content}}</textarea> 
      <br><br><br>

      <input type="submit" value="Edit">

    </form>
    {% for message in get_flashed_messages() %}
    <div class="flash">{{ message }}</div>
    {% endfor %}


  </div>

</body>

</html>

forum/templates/post/post.html
<!DOCTYPE html>
<html lang="en">

<head>
  <title>post.title</title>

  <link rel="stylesheet" href="{{url_for('static',filename='style.css')}}" />

  <style type="text/css">
    body {
      margin:0px;
    }

    div#back {
      margin-left: 10px;
      width: 100%;
      height: 30px;
    }

    div#title {
      text-align:center;
      width: 100%;
      height: 50px;
      font-size:xx-large;
      font-weight: bolder;
    }

    div#information {
      text-align:center;
      width: 100%;
      height: 100px;
      font-weight:lighter;
    }

    div#content {
      padding-left: 20%;
      padding-right: 20%;

      height: 100%;
      word-wrap: break-word;
      width:60%;
    }

    div#header {
      background-color:aliceblue;
    }

    div#edit {
        padding-left: 20%;
        padding-right: 20%;
        width:60%;
        text-align:right;
        line-height: 50px;
        height: 50px;
    }

    div#upvote {

        height: 150px;
        display:inline-block;
        margin:10px;
        width: 150px;
    }

    div#reply {

        display:inline-block;
  

    }

    div#interact {    
      padding-top: 20px;
      text-align:center;
    }

    #box {  
      width:1000px;
      height: 110px;
      padding: 10px;
    }

    #send {
      height: 95px;
      width:75px;
      text-align: center;
      
    }

    div#reply_post {
      padding-left: 20%;
      padding-right: 20%;
      width: 100%;
      height: 100%;
      word-wrap: break-word;
      width:60%;
      background-color:aliceblue;
    }


    div#Reply_title {
      text-align:center;
      width: 100%;
      height: 50px;
      font-size:x-large;
      font-weight: bold;
    }

    div#information_reply {
      text-align:right;
      width: 100%;
      font-weight:lighter;
    }
  



  </style>


</head>

<body>

  <div id = header>
    <div id = back>
      <a class="action" href="{{ url_for('index.index') }}">Back</a>
      
      {% if session.get('user_id') %}
        <li><span>{{ 'Welcome, '+ session.get('user_id') }}</span>
      {% endif %}
  
    </div>

    <div id = title>
      <p>{{post.title}}</p>
    </div>

    <div id = information>
      <p>Author: {{post.author}}</p>
      <p>Create_datetime: {{post.create_datetime}}</p>
    </div>

  </div>

  <div id = content>
    <p>{{post.content}}</p>
  </div>



  <div id = edit>
    {% if session.get('user_id') == post['author'] %}
      <a class="action" href="{{ url_for('post.edit_post', id=post['id']) }}">Edit</a>
      <a class="action" href="{{ url_for('post.delete_post', id=post['id']) }}">Delete</a>
    {% endif %}
  </div>


  <div id = interact>
    <div id = reply>
      <form method="post" action="{{url_for('post.reply', id=post.id)}}">
        <!-- <input type="content" name="content" id="box"> -->
        <textarea  name="content" id="box"></textarea> 
    </div>


    <div id = upvote>

        <input type="submit" value='Reply' id = "send">
        </form>
        
        {% if upvoted %}
        <form method="post" action="{{url_for('post.unupvote', id=post.id)}}">
          <input type="submit" style="background-color:aquamarine" value='Upvoted | {{upvote_num}}'>
        </form>
        {% else %}
        <form method="post" action="{{url_for('post.upvote', id=post.id)}}">
          <input type="submit" value='Upvote | {{upvote_num}}'>
        </form>
        {% endif %}

        {% if favourited %}
        <form method="post" action="{{url_for('post.unfavourite', id=post.id)}}">
          <input type="submit" style="background-color:aquamarine" value='Favourited'>
        </form>
        {% else %}
        <form method="post" action="{{url_for('post.favourite', id=post.id)}}">
          <input type="submit" value='Favourite'>
        </form>
        {% endif %}
      </div>
    </div>


      {% if replies %}
      <div id = reply_post>
      <div id = Reply_title>
        <p>Replies</p>
      </div>
      {% endif %}
    

      {% for reply in replies %}
      <p>{{reply.content}}</p>
      <br>
      <br>
      <div id = information_reply>
        <p>By {{reply.author}} on {{reply.time}}</p>
      </div>

      {% if not loop.last %}
      <hr>
      {% endif %}
      {% endfor %}
    </div>


</body>

</html>